In [1]:
## 00. PyTorch Fundamenetals


In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.1+cu121


In [3]:
!nvidia-smi

Fri Jul 19 12:14:33 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   49C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

## Tensors

### Creating tensors
PYTorch tensors are created using torch.Tensor() = https://pytorch.org/docs/stable/tensors.html

In [4]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim # ndim - n dimention

0

In [6]:
# Get tensor back as python int
scalar.item()


7

In [7]:
# vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
# MATRIX
MATRIX = torch.tensor([
    [7,8],[9,10]
    ])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
TENSOR.ndim # ndim - number of dimentions

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random tensors
Why random tensors?
Random tensors are important bcz the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.
`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [17]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.1864, 0.7744, 0.8048, 0.8617],
        [0.1672, 0.2017, 0.3600, 0.7491],
        [0.7655, 0.1900, 0.6097, 0.1432]])

In [18]:
random_tensor.ndim

2

In [19]:
random_tensor = torch.rand(1,3,4)
random_tensor

tensor([[[0.3689, 0.5797, 0.0016, 0.8050],
         [0.1442, 0.0522, 0.8982, 0.6786],
         [0.5424, 0.9926, 0.1310, 0.0318]]])

In [20]:
random_tensor.ndim

3

In [21]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3872, 0.5119, 0.5585, 0.5605],
        [0.0222, 0.8623, 0.6042, 0.3269],
        [0.2311, 0.8282, 0.2117, 0.6658]])

In [22]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels (R,G,B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeroes and ones

In [23]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [24]:
# create a tensor of all ones
ones = torch.ones(size=(3,4))

In [25]:
ones.dtype

torch.float32

In [26]:
ones.ndim

2

### creating a range of tensors and tensors-like

In [27]:
# Use torch.range(0, 10)
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
one_to_ten = torch.arange(start=0, end=100, step=2) # torch.range is deprecated
one_to_ten

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
        36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70,
        72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [30]:
one_to_ten = torch.arange(start=0, end=11, step=1)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
# creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes
**Note:** Tensor datatypes is 1 of 3 big errors you'll run into with PyTorch & deep learning. These are tensor attributes
1. Tensors not right datatype
2. Tensor not right shape
3. Tensors not on the right device

In [32]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None)
float_32_tensor

tensor([3., 6., 9.])

In [33]:
float_32_tensor.dtype

torch.float32

In [34]:
float_32_tensor = torch.tensor(
    [3.0, 6.0, 9.0],
    dtype=torch.float16
)
float_32_tensor.dtype

torch.float16

In [35]:
float_32_tensor = torch.tensor(
    [3.0, 6.0, 9.0],
    dtype=None, # what datatype is the tensor (ex: float32, float16)
    device=None, # what device is your tensor on, cpu or gpu!
    requires_grad=False # whether or not to track gradients with this tensor operations
)
float_32_tensor.dtype

torch.float32

In [36]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [37]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [38]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [39]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [40]:
int_64_tensor = torch.tensor([3, 6, 9], dtype=torch.int64)
int_64_tensor

tensor([3, 6, 9])

In [41]:
float_32_tensor * int_64_tensor

tensor([ 9., 36., 81.])

In [42]:
int_long_tensor = torch.tensor([3, 6, 9], dtype=torch.long)
int_long_tensor

tensor([3, 6, 9])

In [43]:
int_long_tensor*int_32_tensor

tensor([ 9, 36, 81])

In [44]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.5444, 0.9403, 0.1456, 0.1140],
        [0.1939, 0.6093, 0.3800, 0.0423],
        [0.0012, 0.7386, 0.7904, 0.7404]])

In [45]:
# Find out details about some tensor
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}")

tensor([[0.5444, 0.9403, 0.1456, 0.1140],
        [0.1939, 0.6093, 0.3800, 0.0423],
        [0.0012, 0.7386, 0.7904, 0.7404]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


### Manipulating Tensors (tensor operations)
Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [46]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [47]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [48]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [49]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [50]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication
Two main ways of performing multiplication in neural networks and deep learning:
1. Element-wise multiplication
2. Matrix multiplication (dot product)

resource: - https://www.mathisfun.com/algebra/metrix-multiplying.html
There are 2 main rules that peforming matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3,2) @ (3,2)` wont work # same as torch.matmul
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
*`(2,3) @ (3,2)` -> `(2,2)`
*`(3,2) @ (2,3)` -> `(3,3)`

In [51]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [52]:
# Matrix multiplicaiton
torch.matmul(tensor, tensor )

tensor(14)

In [53]:
tensor

tensor([1, 2, 3])

In [54]:
# matrix multiplication by hand
1*1+2*2+3*3

14

In [55]:
%%time
value=0
for i in range(len(tensor)):
    value += tensor[i]*tensor[i]
print(value)


tensor(14)
CPU times: user 2.75 ms, sys: 117 µs, total: 2.87 ms
Wall time: 11.7 ms


## one of the most common errors in the DL: shape errors
resource - matrixmultiplication.xyz

In [56]:
torch.matmul(torch.rand(3,10), torch.rand(10,3)) # for multiplication inner dimensions have to match and the result will match the shape of the outer match

tensor([[1.8522, 2.7645, 3.4551],
        [1.7612, 2.0044, 3.0767],
        [1.4975, 1.8826, 2.3915]])

In [58]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                   [3,4],
                   [5,6]])
tensor_B = torch.tensor([[7,10],
                   [8,11],
                   [9,12]])
# torch.mm(tensor_A, tensor_B) # mm short for matmul - matmultiplication
torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [59]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape isssue, we can manipulate the shape of one of our tensors using a **transpose**
A **transpose** switches the axes or dimension of a given tensor

In [60]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [61]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [62]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [63]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = { tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions sample)")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions sample)
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


# Finding the min, max, mean, sum, etc (aggregation)

In [64]:
# Create a tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [65]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [66]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [68]:
# Find the mean
torch.mean(x), x.mean()

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [69]:
# Find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [70]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

# finding the positional min and max

In [71]:
# Create a tensor
x = torch.arange(1,100,10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [72]:
# Find the position in tensor that has minimum with argmin() --> returns index position of target tensor where the minium value occurs
x.argmin(), x.min()

(tensor(0), tensor(1))

In [73]:
x.argmax(), x.max()

(tensor(9), tensor(91))

## Reshaping, stacking, squeezing and unsqueezing tensors
* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all 1 dimensions from a tensor
* Unsqueeze - add a 1 dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [74]:
# Let's create a tensor
import torch
x = torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [75]:
# Add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [76]:
# Add an extra dimension
x_reshaped = x.reshape(9,1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [77]:
# Add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [78]:
# Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [79]:
# changin z changes x (because a view of a tensor shares the same memory as the original)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [80]:
# Stack tensor on top of each other

In [81]:
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [82]:
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [83]:
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [84]:
# torch.squeeze() - removes all single dimentions from a target tensor
print(f"Previous tensor:  {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor:  tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [85]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
New shape: torch.Size([9, 1])


In [86]:
# torch.permute rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224,224,3)) # height, width, color channels (R,G,B)

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2,0,1) # shifts axis 0->1, 1->2, 2->0

print(f"Original shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Original shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [87]:
x_original[0,0,0]=728218
x_original[0,0,0], x_permuted[0,0,0]

(tensor(728218.), tensor(728218.))

  # Indexing (selecting data from tensors)
  ## Indexing with PyTorch is similar to indexing with NumPy.

In [88]:
# Create a tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [89]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [90]:
# Let's index on the middle bracket (dim=1)
x[0][0] # x[0,0] same

tensor([1, 2, 3])

In [91]:
# Let's index on the most inner bracket (last dimensiion)
x[0][1][1]

tensor(5)

In [92]:
x[0,2,2]

tensor(9)

In [93]:
# ":" to select all of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [94]:
# get all values of the 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [95]:
# Get all values of the 0 dimnsion but only the 1 index value of 1st and 2nd dimensiion
x[:, 1, 1]

tensor([5])

In [96]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

## PyTorch tensors & NumPy
NumPy is a library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays.
* Data in Numpy, want in PyTorch tensor ->torch.from_numpy(ndarray)
* PyTorch tensor -> NumPy -> torch.Tensor.numpy()

In [97]:
# NumPy array to tensor
import torch
import numpy

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # warning: when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [98]:
tensor.dtype

torch.float64

In [99]:
# Change the value of array, what will this do do `tensor`?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [100]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [101]:
numpy_tensor.dtype

dtype('float32')

In [102]:
# Change the tensor, what happens to `numpy_tensor`?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [103]:
numpy_tensor = numpy_tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([2., 2., 2., 2., 2., 2., 2.], dtype=float32))

## Reproducibility (trying to take randomout of random)
In short how a neural network learns:

`Start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.
Essentially what the random seed does is "flavour" the randomness.

In [104]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.6168, 0.4056, 0.5870, 0.8254],
        [0.1709, 0.5823, 0.4141, 0.0484],
        [0.5708, 0.8434, 0.8166, 0.4961]])
tensor([[0.7531, 0.5431, 0.3840, 0.2193],
        [0.3524, 0.1517, 0.1616, 0.6707],
        [0.4322, 0.2999, 0.2417, 0.0261]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [105]:
# Let's make some random but reproducible tensors
import torch

# set the random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Extra resources for randomness
- https://pytorch.org/docs/stable/notes/randomness.html
- https://pytorch.org/docs/stable/generated/torch.manual_seed.html

## Running tensors and PyTorch objects on the GPUs (and making faster computations)
GPUs = faster computation of numbers, thanks to CUDA+ NVIDIA hardware + PyTorch working behind the scenes to make everything hunky dory (good)

### 1. Getting a GPU
1. Easiest - Use google colab for a free GPU (options to upgrade as well)
2. Use your own GPU
3. use cloud computing - GCP, AWS, Azure, these services allow you to rent computers onm the cloud and access them.

In [111]:
!nvidia-smi

Fri Jul 19 12:30:09 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   66C    P0              28W /  70W |    105MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

# 2. check for GPU ccess with PyTorch

In [106]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

For PyTorch since it's capable of running compute on the GPU or CPU, it's best practice to setup device agnostic code: https://pytorch.org/docs/stable/notes/cuda.html#best-practices

ex: run on the GPU if available, else default to CPU

In [107]:
#  setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [108]:
# count number of devcies
torch.cuda.device_count()


1

In [109]:
# Putting tensors (and models)
tensor = torch.tensor([1,2,3])

# Tensor not on GPU
print(tensor, tensor.device)


tensor([1, 2, 3]) cpu


In [110]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu


tensor([1, 2, 3], device='cuda:0')

# 3. Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations.

In [114]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1,2,3])

# Tensor not on the GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [115]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the CPU

In [117]:
# If tensor is on the GPU, can't transform it to NumPy
tensor_on_gpu.numpy() # error out

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [118]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [120]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')