# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
# Import torch
import torch

# Create random tensor
torch.rand(7,7)

tensor([[6.8092e-01, 2.1233e-01, 3.3419e-01, 9.1451e-01, 4.0330e-01, 6.7056e-01,
         7.0953e-01],
        [3.7941e-02, 3.4226e-01, 1.6551e-01, 1.5835e-01, 5.4150e-01, 6.0400e-01,
         7.7552e-01],
        [6.1010e-01, 4.0883e-01, 2.9204e-01, 6.2732e-01, 7.7338e-01, 7.3524e-01,
         6.4939e-01],
        [1.4465e-01, 5.7017e-01, 2.6446e-01, 6.9676e-01, 1.9693e-04, 9.6229e-01,
         7.5945e-01],
        [3.4799e-01, 8.3979e-01, 9.6882e-01, 5.4059e-01, 2.5406e-01, 1.8808e-01,
         6.3556e-01],
        [5.3026e-01, 6.9674e-01, 5.1410e-01, 8.5120e-01, 4.9563e-01, 2.8966e-01,
         9.8036e-01],
        [9.6240e-01, 1.8507e-01, 3.0481e-01, 1.2541e-01, 4.9630e-01, 2.4272e-01,
         3.7750e-01]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [13]:
# Create another random tensor
rand_tensor = torch.rand(7,7)

rand_tensor1 = torch.rand(1,7)
# Perform matrix multiplication
rand_tensor.matmul(rand_tensor1.T)

tensor([[2.3581],
        [2.1042],
        [1.3926],
        [0.7091],
        [1.2993],
        [1.3420],
        [2.6635]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [15]:
# Set manual seed
RANDOM_SEED = 0

# Create two random tensors
torch.manual_seed(RANDOM_SEED)
random_tensor_1 = torch.rand(7,7)

torch.manual_seed(RANDOM_SEED)
random_tensor_2 = torch.rand(1,7)

# Matrix multiply tensors
random_tensor_1.matmul(random_tensor_2.T)

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [16]:
# Set random seed on the GPU
torch.rand(7,7).cuda()

tensor([[0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783],
        [0.4820, 0.8198, 0.9971, 0.6984, 0.5675, 0.8352, 0.2056]],
       device='cuda:0')


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [21]:
# Set random seed
RANDOM_SEED=1

# Check for access to GPU
torch.cuda.is_available()

# Create two random tensors on GPU
tensor_gpu1= torch.rand(2,3).cuda()
tensor_gpu2= torch.rand(3,3).cuda()


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [25]:
# Perform matmul on tensor_A and tensor_B
tensor_gpu_out = tensor_gpu1.matmul(tensor_gpu2.T)

### 8. Find the maximum and minimum values of the output of 7.

In [27]:
# Find max
tensor_gpu_out.max()
# Find min
tensor_gpu_out.min(), tensor_gpu_out.max()

(tensor(0.5721, device='cuda:0'), tensor(1.4732, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [28]:
# Find arg max
tensor_gpu_out.argmax()

# Find arg min
tensor_gpu_out.argmin(), tensor_gpu_out.argmax()

(tensor(0, device='cuda:0'), tensor(1, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [30]:
# Set seed
RANDOM_SEED = 7

# Create random tensor
tensor_1 = torch.rand(1,1,1,10)

# Remove single dimensions from a target tensor
tensor_1.squeeze()

# Remove single dimensions
tensor_1.squeeze().shape

# Print out tensors and their shapes
print(tensor_1)
print(tensor_1.shape)


tensor([[[[0.7497, 0.6047, 0.1100, 0.2121, 0.9704, 0.8369, 0.2820, 0.3742,
           0.0237, 0.4910]]]])
torch.Size([1, 1, 1, 10])
